name: build-wheels
on:
  # push:
  #   branches: [main]
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ pkg-config libboost-all-dev
          python -m pip install --upgrade pip
          python -m pip install build meson ninja
      - name: Build wheel
        run: |
          meson setup --reconfigure buildDir --buildtype=debug
          python -m build --wheel
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-linux
          path: dist/*.whl
          if-no-files-found: error
      # - name: Publish to Artifactory
      #   run: |
      #     python -m pip install --upgrade twine
      #     twine upload \
      #       --repository-url https://<artifactory-url>/api/pypi/<repo>/ \
      #       --username USERNAME \
      #       --password PASSWORD \
      #       dist/*.whl
  build-windows:
    runs-on: windows-latest
  steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ucrt64
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-python
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
      - name: Run unittests
        shell: msys2 {0}
        run: |
          meson setup --reconfigure buildDir --buildtype=debug
          python -m build --wheel
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-windows
          path: dist/*.whl
          if-no-files-found: error
      # - name: Publish to Artifactory
      #   run: |
      #     python -m pip install --upgrade twine
      #     twine upload \
      #       --repository-url https://<artifactory-url>/api/pypi/<repo>/ \
      #       --username USERNAME \
      #       --password PASSWORD \
      #       dist/*.whl
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          brew update
          brew install gcc boost pkg-config
          python -m pip install --upgrade pip
          python -m pip install build meson ninja
      - name: Build wheel
        run: |
          meson setup --reconfigure buildDir --buildtype=debug
          python -m build --wheel
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-mac
          path: dist/*.whl
          if-no-files-found: error
      # - name: Publish to Artifactory
      #   run: |
      #     python -m pip install --upgrade twine
      #     twine upload \
      #       --repository-url https://<artifactory-url>/api/pypi/<repo>/ \
      #       --username USERNAME \
      #       --password PASSWORD \
      #       dist/*.whl
